### ISSUE TITLE
Bug: Joining arrays in YAML adds invalid `-`

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#88]
given this array (with `|` as cursor position)
```yml
no-empty:
  - wa|rn
  - allowEmptyCatch: true
 ```

joining will result in this:
```yml
  no-empty: [ warn, - { allowEmptyCatch: true } ]
 ```

which is invalid yaml, as it should be this:
```yml
  no-empty: [ warn, { allowEmptyCatch: true } ]
 ```
